s/# CONFIG_OSCAM_ADDON_LCDSUPPORT is not set/CONFIG_OSCAM_ADDON_LCDSUPPORT=y/
s/# CONFIG_OSCAM_ADDON_LEDSUPPORT is not set/CONFIG_OSCAM_ADDON_LEDSUPPORT=y/
s/# CONFIG_OSCAM_ADDON_IPV6SUPPORT is not set/CONFIG_OSCAM_ADDON_IPV6SUPPORT=y/
s/# CONFIG_PACKAGE_list-smargo is not set/CONFIG_PACKAGE_list-smargo=y/
